---
title: "flipped"
format: 
  html:
    embed-resources: true
    code-tools: true
    code-fold: true
    toc: true
    number-sections: false
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r}
library(dplyr)
library(purrr)
library(lubridate)
library(progress)
devtools::load_all("../")
```

```{r}
affiliation_dates
```


```{r}
#edgelist for orgs
start <- min(affiliation_dates$Start.Date, na.rm = TRUE)
end <- max(affiliation_dates$Start.Date, na.rm = TRUE)
edgelist_orgs <- get_edgelist_orgs(affiliation_dates, "None", start, end, 1)
```

```{r}
write.csv(edgelist_orgs,"./edgelist-orgs.csv", row.names = FALSE)
```


```{r}
metrics <- get_all_metrics_orgs(affiliation_dates, "None", 1)
```

```{r}
write.csv(metrics,"./all_metrics_by_month_orgs.csv", row.names = FALSE)
```

```{r}
all_metrics_by_month_orgs <- read.csv("all_metrics_by_month_orgs.csv")
#save(all_metrics_by_month_orgs, file = "all_metrics_by_month_orgs.rda")
```

```{r}
sapply(all_metrics_by_month_orgs, class)
```


```{r}
all_metrics_by_month_orgs$Start.Date = as.Date(all_metrics_by_month_orgs$Start.Date)
all_metrics_by_month_orgs$End.Date = as.Date(all_metrics_by_month_orgs$End.Date)
```




```{r}
affiliation_dates %>%
  distinct(Org.ID, Member.ID, RT.Affiliation) %>%
  group_by(Org.ID, RT.Affiliation) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = "RT.Affiliation", values_from = "count", values_fill = 0) %>%
  group_by(Org.ID) %>%
  summarize(across(.cols = c("Opposition", "Church", "Government", "Expert"), sum)) %>%
  mutate(Total = Opposition + Church + Government + Expert)
```



```{r}
affiliation_dates %>%
  distinct(Org.ID, Member.ID, RT.Affiliation) %>%
  group_by(Org.ID) %>%
  summarize(count = n())
```


